"""empty message

Revision ID: 13d366f44c57
Revises: e7399bb22134
Create Date: 2024-12-12 12:24:59.996981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d366f44c57'
down_revision: Union[str, None] = 'e7399bb22134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('parent_hash', sa.String(length=40), nullable=True),
    sa.Column('message', sa.JSON(), nullable=False),
    sa.Column('vm_state', sa.JSON(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commit_hash')
    )
    op.create_index('idx_commit_hash', 'commits', ['commit_hash'], unique=False)
    op.create_index('idx_commit_parent', 'commits', ['parent_hash'], unique=False)
    op.create_index('idx_commit_task_time', 'commits', ['task_id', 'committed_at'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('head_commit_hash', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['head_commit_hash'], ['commits.commit_hash'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'task_id', name='uk_branch_name_task')
    )
    op.create_index('idx_branch_name_task', 'branches', ['name', 'task_id'], unique=False)
    op.create_index('idx_branch_task_id', 'branches', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_branch_task_id', table_name='branches')
    op.drop_index('idx_branch_name_task', table_name='branches')
    op.drop_table('branches')
    op.drop_index('idx_commit_task_time', table_name='commits')
    op.drop_index('idx_commit_parent', table_name='commits')
    op.drop_index('idx_commit_hash', table_name='commits')
    op.drop_table('commits')
    # ### end Alembic commands ###
