"""empty message

Revision ID: 2750b07f8551
Revises: 7a5e53530c2f
Create Date: 2024-11-08 11:21:54.281487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2750b07f8551'
down_revision: Union[str, None] = '7a5e53530c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'best_plan',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'best_plan',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
