"""empty message

Revision ID: 2b321abca06d
Revises: 13d366f44c57
Create Date: 2025-01-07 10:03:50.482875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b321abca06d'
down_revision: Union[str, None] = '13d366f44c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('evaluation_status', sa.Enum('NOT_EVALUATED', 'APPROVED', 'REJECTED', name='evaluation_status'), server_default='NOT_EVALUATED', nullable=True, comment='The evaluation status of the task by the LLM.'))
    op.add_column('tasks', sa.Column('evaluation_reason', sa.Text(), nullable=True, comment='Reason for rejection if the task is not approved.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'evaluation_reason')
    op.drop_column('tasks', 'evaluation_status')
    # ### end Alembic commands ###
