"""empty message

Revision ID: 463f3528ed11
Revises: 338c33e23e19
Create Date: 2024-11-13 19:35:29.148154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463f3528ed11'
down_revision: Union[str, None] = '338c33e23e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('labels', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labels', 'updated_at')
    op.drop_column('labels', 'created_at')
    # ### end Alembic commands ###
