"""empty message

Revision ID: 4bee4d6f9670
Revises: 463f3528ed11
Create Date: 2024-11-13 20:38:25.291021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bee4d6f9670'
down_revision: Union[str, None] = '463f3528ed11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='labels')
    op.drop_constraint('fk_1', 'labels', type_='foreignkey')
    op.create_foreign_key(None, 'labels', 'labels', ['parent_id'], ['id'])
    op.drop_constraint('fk_1', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'labels', ['label_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('fk_1', 'tasks', 'labels', ['label_id'], ['id'], referent_schema='stackvm')
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.create_foreign_key('fk_1', 'labels', 'labels', ['parent_id'], ['id'], referent_schema='stackvm')
    op.create_index('name', 'labels', ['name'], unique=True)
    # ### end Alembic commands ###
