"""empty message

Revision ID: 703f49d30beb
Revises: 2b321abca06d
Create Date: 2025-01-13 14:52:01.992468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '703f49d30beb'
down_revision: Union[str, None] = '2b321abca06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('human_evaluation_status', sa.Enum('NOT_EVALUATED', 'APPROVED', 'REJECTED', name='evaluation_status'), server_default='NOT_EVALUATED', nullable=True, comment='The evaluation status of the task by the LLM.'))
    op.add_column('tasks', sa.Column('human_feedback', sa.Text(), nullable=True, comment='Reason for rejection if the task is not approved.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'human_feedback')
    op.drop_column('tasks', 'human_evaluation_status')
    # ### end Alembic commands ###
