"""empty message

Revision ID: 76f42c78b501
Revises: ec605ce5a7de
Create Date: 2025-01-19 15:19:05.117971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '76f42c78b501'
down_revision: Union[str, None] = 'ec605ce5a7de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labels', 'namespace_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.add_column('tasks', sa.Column('namespace_name', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_tasks_namespace_name'), 'tasks', ['namespace_name'], unique=False)
    op.create_foreign_key('fk_tasks_namespace', 'tasks', 'namespaces', ['namespace_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_namespace', 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_namespace_name'), table_name='tasks')
    op.drop_column('tasks', 'namespace_name')
    op.alter_column('labels', 'namespace_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
