"""empty message

Revision ID: 897d73d1c590
Revises: 7d4f94c1c9ca
Create Date: 2025-01-18 12:15:53.545937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897d73d1c590'
down_revision: Union[str, None] = '7d4f94c1c9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('namespace', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_labels_namespace'), 'labels', ['namespace'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labels_namespace'), table_name='labels')
    op.drop_column('labels', 'namespace')
    # ### end Alembic commands ###
