"""empty message

Revision ID: e7399bb22134
Revises: e6b25f9da7fb
Create Date: 2024-11-19 11:24:29.730440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7399bb22134'
down_revision: Union[str, None] = 'e6b25f9da7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('labels', sa.Column('best_practices', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labels', 'best_practices')
    op.drop_column('labels', 'description')
    # ### end Alembic commands ###
