"""empty message

Revision ID: ec605ce5a7de
Revises: 7d4f94c1c9ca
Create Date: 2025-01-18 20:06:00.478787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec605ce5a7de'
down_revision: Union[str, None] = '7d4f94c1c9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('namespaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('allowed_tools', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_namespaces_id'), 'namespaces', ['id'], unique=False)
    op.create_index(op.f('ix_namespaces_name'), 'namespaces', ['name'], unique=True)
    op.add_column('labels', sa.Column('namespace_name', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_labels_namespace_name'), 'labels', ['namespace_name'], unique=False)
    op.create_foreign_key('fk_labels_namespace_name', 'labels', 'namespaces', ['namespace_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_labels_namespace_name', 'labels', type_='foreignkey')
    op.drop_index(op.f('ix_labels_namespace_name'), table_name='labels')
    op.drop_column('labels', 'namespace_name')
    op.drop_index(op.f('ix_namespaces_name'), table_name='namespaces')
    op.drop_index(op.f('ix_namespaces_id'), table_name='namespaces')
    op.drop_table('namespaces')
    # ### end Alembic commands ###
